### ISSUE TITLE
Issues with installation

### ISSUE THREAD

**Issue by annekegh** [tskora/pyBrown#1]
Dear authors,

I am trying to install the package, but I am having trouble.
First I searched about lapack and I found some libraries with the locate command, and I passed them to the configure command.
During the "make" step, I get an error 
   'aclocal-1.16' is missing on your system
and I have no idea what to do next. Automake is installed, aclocal also, but the version 1.16 is not available in the repository.
What should I do next?

Kind regards

**Comment by tskora** [comment]
Dear annekegh,

I assume, that when running ./configure there are no errors?
Maybe cleaning and rerunning autotools will help:
```
cp README.md README
make clean
make distclean
autoreconf -f -i
```
The first line is because one of the scripts needs to see README file, and is not satisfied with README.md.
After those 4 lines run configure and make like previously.

Kind regards,
Tomasz

**Comment by annekegh** [comment]
Dear Tomasz,

Thanks so much for your quick answer. Unfortunately, the above commands didn't solve it. But I downloaded a zip-file (which should preserve timestamps) and put the source in a different directory. Then I could do the configure command and make. For the third step, make install, I get an error again:

```
make install 
Making install in src
make[1]: Entering directory '/home/an/code/pyBrown-master/src'
Making install in bdsim
make[2]: Entering directory '/home/an/code/pyBrown-master/src/bdsim'
Making install in clib
make[3]: Entering directory '/home/an/code/pyBrown-master/src/bdsim/clib'
make[4]: Entering directory '/home/an/code/pyBrown-master/src/bdsim/clib'
 /bin/mkdir -p '/usr/local/lib'
 /bin/bash ../../../libtool   --mode=install /usr/bin/install -c   libpyBrown.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libpyBrown.so.0.1.0 /usr/local/lib/libpyBrown.so.0.1.0
/usr/bin/install: cannot create regular file '/usr/local/lib/libpyBrown.so.0.1.0': Permission denied
Makefile:374: recipe for target 'install-libLTLIBRARIES' failed
make[4]: *** [install-libLTLIBRARIES] Error 1
make[4]: Leaving directory '/home/an/code/pyBrown-master/src/bdsim/clib'
Makefile:551: recipe for target 'install-am' failed
make[3]: *** [install-am] Error 2
make[3]: Leaving directory '/home/an/code/pyBrown-master/src/bdsim/clib'
Makefile:437: recipe for target 'install-recursive' failed
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory '/home/an/code/pyBrown-master/src/bdsim'
Makefile:360: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/an/code/pyBrown-master/src'
Makefile:391: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
```

If I then use sudo make install, I get again an error

```
Making install in src
make[1]: Entering directory '/home/an/code/pyBrown-master/src'
Making install in bdsim
make[2]: Entering directory '/home/an/code/pyBrown-master/src/bdsim'
Making install in clib
make[3]: Entering directory '/home/an/code/pyBrown-master/src/bdsim/clib'
make[4]: Entering directory '/home/an/code/pyBrown-master/src/bdsim/clib'
 /bin/mkdir -p '/usr/local/lib'
 /bin/bash ../../../libtool   --mode=install /usr/bin/install -c   libpyBrown.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libpyBrown.so.0.1.0 /usr/local/lib/libpyBrown.so.0.1.0
libtool: install: (cd /usr/local/lib && { ln -s -f libpyBrown.so.0.1.0 libpyBrown.so.0 || { rm -f libpyBrown.so.0 && ln -s libpyBrown.so.0.1.0 libpyBrown.so.0; }; })
libtool: install: (cd /usr/local/lib && { ln -s -f libpyBrown.so.0.1.0 libpyBrown.so || { rm -f libpyBrown.so && ln -s libpyBrown.so.0.1.0 libpyBrown.so; }; })
libtool: install: /usr/bin/install -c .libs/libpyBrown.lai /usr/local/lib/libpyBrown.la
libtool: install: /usr/bin/install -c .libs/libpyBrown.a /usr/local/lib/libpyBrown.a
libtool: install: chmod 644 /usr/local/lib/libpyBrown.a
libtool: install: ranlib /usr/local/lib/libpyBrown.a
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/sbin" ldconfig -n /usr/local/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /usr/local/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
make[4]: Nothing to be done for 'install-data-am'.
make[4]: Leaving directory '/home/an/code/pyBrown-master/src/bdsim/clib'
make[3]: Leaving directory '/home/an/code/pyBrown-master/src/bdsim/clib'
Making install in tests
make[3]: Entering directory '/home/an/code/pyBrown-master/src/bdsim/tests'
make[4]: Entering directory '/home/an/code/pyBrown-master/src/bdsim/tests'
make[4]: Nothing to be done for 'install-exec-am'.
make[4]: Nothing to be done for 'install-data-am'.
make[4]: Leaving directory '/home/an/code/pyBrown-master/src/bdsim/tests'
make[3]: Leaving directory '/home/an/code/pyBrown-master/src/bdsim/tests'
make[3]: Entering directory '/home/an/code/pyBrown-master/src/bdsim'
make[4]: Entering directory '/home/an/code/pyBrown-master/src/bdsim'
 /bin/mkdir -p '/usr/local/bin'
 /usr/bin/install -c BD.py BD-restart.py BD-NAM.py BD-NAM-restart.py '/usr/local/bin'
make  install-exec-hook
make[5]: Entering directory '/home/an/code/pyBrown-master/src/bdsim'
cp --parents pyBrown/bead.py pyBrown/box.py pyBrown/diffusion.py pyBrown/input.py pyBrown/interactions.py pyBrown/output.py pyBrown/plane.py pyBrown/reactions.py `python3 -m site --user-site`
cp: target '/home/an/.local/lib/python3.6/site-packages' is not a directory
Makefile:716: recipe for target 'install-exec-hook' failed
make[5]: *** [install-exec-hook] Error 1
make[5]: Leaving directory '/home/an/code/pyBrown-master/src/bdsim'
Makefile:652: recipe for target 'install-exec-am' failed
make[4]: *** [install-exec-am] Error 2
make[4]: Leaving directory '/home/an/code/pyBrown-master/src/bdsim'
Makefile:601: recipe for target 'install-am' failed
make[3]: *** [install-am] Error 2
make[3]: Leaving directory '/home/an/code/pyBrown-master/src/bdsim'
Makefile:437: recipe for target 'install-recursive' failed
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory '/home/an/code/pyBrown-master/src/bdsim'
Makefile:360: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/an/code/pyBrown-master/src'
Makefile:391: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
```
Advice would be appreciated.
Kind regards,
An

**Comment by tskora** [comment]
Dear An,

I recognize this issue. You have to manually create that lacking site-packages directory, ie., if `/home/an/.local/lib/python3.6` exists and does not contain `site-packages/`, then type
```
mkdir /home/an/.local/lib/python3.6/site-packages/
```
I have not yet found how to avoid that, I see it from time to time on HPC clusters.

Kind regards,
Tomasz

**Comment by annekegh** [comment]
Dear Tomasz,

I made the .local directory and make install finished without errors.
The program doesn't run yet, unfortunately:

```
$ BD.py -h
Traceback (most recent call last):
  File "/usr/local/bin/BD.py", line 26, in <module>
    from pyBrown.box import Box
ModuleNotFoundError: No module named 'pyBrown'
$ which BD.py
/usr/local/bin/BD.py
```

This is some information about python:

```
$ python3 -m site --user-site
/home/an/.local/lib/python3.7/site-packages
$ ll /home/an/.local/lib/python3.7/site-packages
ls: cannot access '/home/an/.local/lib/python3.7/site-packages': No such file or directory
$ ll /home/an/.local/lib/python3.6/site-packages
total 4
drwx------ 2 root root 4096 Aug 23 09:10 pyBrown
$ ll /home/an/.local/lib/python3.6/site-packages/pyBrown/
ls: cannot open directory '/home/an/.local/lib/python3.6/site-packages/pyBrown/': Permission denied
$ sudo ls /home/an/.local/lib/python3.6/site-packages/pyBrown/ -l
total 116
-rw-r--r-- 1 root root 13520 Aug 23 09:10 bead.py
-rw-r--r-- 1 root root 24065 Aug 23 09:10 box.py
-rw-r--r-- 1 root root  4531 Aug 23 09:10 diffusion.py
-rw-r--r-- 1 root root  6328 Aug 23 09:10 input.py
-rw-r--r-- 1 root root 25169 Aug 23 09:10 interactions.py
-rw-r--r-- 1 root root  4758 Aug 23 09:10 output.py
-rw-r--r-- 1 root root  4135 Aug 23 09:10 plane.py
-rw-r--r-- 1 root root 15308 Aug 23 09:10 reactions.py
$ which python
/home/an/lib/anaconda3/bin/python
$ which python3
/home/an/lib/anaconda3/bin/python3
$ python --version
Python 3.7.6
$ python3 --version
Python 3.7.6
```

**Comment by tskora** [comment]
Ok, now the question is where your `python3` looks for installed modules, because it cannot find `pyBrown`. You can check it by running `python3` from the terminal and then typing:
```
import sys
sys.path
```
Is `'/home/an/.local/lib/python3.6/site-packages'` and/or `'/home/an/.local/lib/python3.7/site-packages'` among the listed directories?
In principle Makefile/Configure pipeline should choose a directory which is there, so if it is not, the problem is on our side and we have to correct the scripts.

Workaround is to append some directories to that list. The list is build based on the environment variable `PYTHONPATH`. You can add more directories to `PYTHONPATH` by adding a following line:
```
export PYTHONPATH=$PYTHONPATH:/home/an/.local/lib/python3.6/site-packages:/home/an/.local/lib/python3.7/site-packages
```
to your `~/.bash_profile` or `~/.zshrc` (depending on what shell you use).
Then, the console has to be restarted.
You can check whether now those are listed by `sys.path`.
Hope it helps with running `BD.py`.

**Comment by annekegh** [comment]
Dear Tomasz,

Thanks for working on this with me. Unfortunately, changing the PYTHONPATH did not fix it.
The previous error was
```
    from pyBrown.box import Box
ModuleNotFoundError: No module named 'pyBrown'
```
Now the error is
```
$ BD.py --version
Traceback (most recent call last):
  File "/usr/local/bin/BD.py", line 26, in <module>
    from pyBrown.box import Box
ModuleNotFoundError: No module named 'pyBrown.box'
```
It seems that the .local folder is not found by BD.py. I am using anaconda. Python (python 3.7) is used in my anaconda environment but pybrown puts the pybrown *py files this .local (root) folder.

```
$ python
Python 3.7.6 (default, Jan  8 2020, 19:59:22)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/home/an', '/home/an/.local/lib/python3.6/site-packages', '/home/an/lib/anaconda3/lib/python37.zip', '/home/an/lib/anaconda3/lib/python3.7', '/home/an/lib/anaconda3/lib/python3.7/lib-dynload', '/home/an/lib/anaconda3/lib/python3.7/site-packages', '/home/an/lib/anaconda3/lib/python3.7/site-packages/pyretis-3.0.0.dev0-py3.7.egg']
```
Kind regards,
An
